# Generated by Django 2.1 on 2018-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('option_one', models.CharField(max_length=250)),
                ('option_two', models.CharField(max_length=250)),
                ('option_three', models.CharField(max_length=250)),
                ('option_four', models.CharField(max_length=250)),
                ('ans', models.CharField(max_length=250)),
            ],
        ),
    ]
